site_name: "Ressources de Terminale NSI"
site_author: Fabrice Perez
site_url: https://eipaca.github.io/NSI-T/

site_description: >-
  Ressources pour le cours de Terminale NSI de l'Ecole Internationale PACA

repo_url: https://github.com/eipaca/NSI-T

copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> Mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0 International</a>.


theme:
  name: material
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.prune 
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

  logo: assets/logo-ecole-internationale-paca-manosque.png

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/log-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16




extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # enables native support for Mermaid.js diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  #  enables content tabs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


  # Page tree
nav:
  - A propos: index.md
  - Langages et programmation: 
    - langages-et-programmation/index.md
    - Programme en tant que donnée, Calculabilité, Problème de l'arrêt: langages-et-programmation/1-programme-en-tant-que-donnee-calculabilite-probleme-arret.md
    - Récursivité: langages-et-programmation/2-recursivite.md
    - Modularité: langages-et-programmation/3-modularite.md
    - Paradigmes de programmation: langages-et-programmation/4-paradigmes-de-programmation.md
    - Mise au point des programmes et gestion des bugs: langages-et-programmation/5-mise-au-point-gestion-bugs.md
  - Bases de données: 
    - bases-de-donnees/index.md
    - Modélisation conceptuelle: bases-de-donnees/1-modelisation-conceptuelle.md
    - Conception logique - le modèle relationnel: bases-de-donnees/2-conception-logique-modele-relationnel.md
    - Conception physique - SGBD relationnel: bases-de-donnees/3-conception-physique-sgbd-relationnel.md
    - Langage SQL: bases-de-donnees/4-langage-sql.md
  # - Structures de données:
  # - Structures de données, interface et implémentation
  #  - Vocabulaire de la programmation objet
 #  - Listes, piles, files 
 #  - Arbres 
 #  - Graphes
  # Architectures matérielles, systèmes d'exploitation et réseaux:
 #  -Composants intégrés d’un système sur puce.
 # -Gestion des processus et des ressources par un système d'exploitation
 # -Protocoles de routage
 # -Sécurisation des communications
 # Algorithmique:
 #Algorithmes sur les arbres binaires et sur les arbres binaires de recherche
 #Algorithmes sur les graphes
 #Méthode « diviser pour régner »
 #Programmation dynamique
 #Recherche textuelle
